---
- name: 'check if overlay {{ olcOverlay }} already exists for {{ olcDatabase }}'
  shell: '{{ ldapsearch }} -b "{{ olcDatabase }}" "(&(objectClass=olcOverlayConfig)(olcOverlay={{ olcOverlay }}))" olcOverlay | grep "^olcOverlay:.*{{ olcOverlay }}" | wc -l'
  register: overlay_status

- name: parse overlay status
  set_fact:
    overlay_exists: '{{ overlay_status.stdout_lines[0]|int > 0 }}'

- name: 'generate ldif for loading overlay {{ olcOverlay }} for {{ olcDatabase }}'
  template:
    src: overlay.ldif.j2
    dest: '{{ ldif_overlay }}'
  when: not overlay_exists

- name: 'add overlay {{ olcOverlay }} to {{ olcDatabase }}'
  shell: '{{ ldapmodify }} -f {{ ldif_overlay }}'
  when: not overlay_exists
