---
- name: 'check if {{ olcModuleName }} is already loaded'
  shell: "{{ ldapsearch }} -b cn=config '(&(objectClass=olcModuleList)(olcModuleLoad={{ olcModuleName }}))' olcModuleLoad | grep '^olcModuleLoad:.*{{ olcModuleName }}' | wc -l"
  register: module_check

- name: parse module check result
  set_fact:
    module_exists: '{{ module_check.stdout_lines[0]|int > 0 }}'

- name: 'generate ldif for {{ olcModuleName }}'
  template:
    src: module.ldif.j2
    dest: '{{ ldif_module }}'
  when: not module_exists

- name: 'load module {{ olcModuleName }}'
  shell: '{{ ldapmodify }} -f {{ ldif_module }}'
  when: not module_exists
