---
- name: generate secret
  set_fact:
    secret: secret

- name: encrypt secret
  shell: 'slappasswd -s {{ secret }}'
  register: secret_encrypted

- set_fact:
    secret_encrypted: '{{ secret_encrypted.stdout_lines[0] }}'
