---
- name: generate secret
  shell: 'slappasswd -n -g'
  register: secret
  run_once: yes

- name: parse generated secret
  set_fact:
    secret: '{{ secret.stdout_lines[0] }}'

- name: encrypt secret
  shell: 'slappasswd -s {{ secret }}'
  register: secret_encrypted

- set_fact:
    secret_encrypted: '{{ secret_encrypted.stdout_lines[0] }}'
