---
- name: set filenames under workdir
  set_fact:
    ldif_stage_1: '{{ workdir }}/stage1.ldif'
    ldif_stage_2: '{{ workdir }}/stage2.ldif'
    ldif_module: '{{ workdir }}/module.ldif'
    ldapsearch: 'ldapsearch -Y EXTERNAL -H ldapi:///'
    ldapmodify: 'ldapmodify -Y EXTERNAL -H ldapi:///'
    olcModules:
    - syncprov.la
    olcModulePath: /usr/lib/ldap
