---
- name: set filenames under workdir
  set_fact:
    ldif_stage_1: '{{ workdir }}/stage1.ldif'
    ldif_stage_2: '{{ workdir }}/stage2.ldif'
    ldif_module: '{{ workdir }}/module.ldif'
    ldif_overlay: '{{ workdir }}/overlay.ldif'
    ldapsearch: 'ldapsearch -Y EXTERNAL -H ldapi:///'
    ldapmodify: 'ldapmodify -Y EXTERNAL -H ldapi:///'
    olcModules:
    - syncprov
    olcModulePath: /usr/lib/ldap
    olcOverlays:
    - syncprov
    ldap_url: 'ldap://{{ inventory_hostname }}'
